### ISSUE TITLE
Performance test

### ISSUE THREAD

**Issue by nu8** [ohler55/ojg#15]
I see this comment:

> Both the Ruby Oj and the C parser OjC are the best performers in their
> respective languages.

https://github.com/ohler55/ojg/blob/master/design.md

but is any data available to back this up? For example I would suspect that this
has higher performance:

https://github.com/simdjson/simdjson

even the site itself doesnt have any evidence:

https://github.com/ohler55/ojc#benchmarks

**Comment by ohler55** [comment]
Benchmarks were added to the OjC repo that show OjC is 2.6 times faster than simdjson at least for the simple log entry parsing in the benchmark.

**Comment by nu8** [comment]
Looks good, thank you!

**Comment by nu8** [comment]
I am reopening this, as it seems the results are not current reproducible:

https://news.ycombinator.com/item?id=23739252

**Comment by ohler55** [comment]
I removed the entry in the README.md. You are right. With a straight compile they are but with optimization simdjson gets a huge boost. You can open an issue in the OjC repo if you like instead of here but OjC no longer has the benchmark results not reference in the README. For this repo, the design.md no longer claims to my C parser is the fastest.

**Comment by nu8** [comment]
thanks for update
