### ISSUE TITLE
 Floating point precision loss issue

### ISSUE THREAD

**Issue by Cchiyi** [ohler55/ojg#187]
jsonpath: `$.data.Price`

json：
```json
{
  "data": {
     "Price": 3.78
  }
}

```
my code is
```go
func Eval(jsonSchema string, path string) (string, error) {
	obj, err := oj.ParseString(jsonSchema)
	if err != nil {
		return "", errors.Wrapf(err, "parse json error")
	}
	x, err := jp.ParseString(path)
	if err != nil {
		return "", errors.Wrapf(err, "parse json error")
	}
	evalRes := x.Get(obj)
	jsonByte, err := oj.Marshal(evalRes)
	if err != nil {
		return "", errors.Wrapf(err, "parse json error")
	}
	return string(jsonByte), nil
}

```
I execute `Eval()` and I got 3.7800000000000002， how can I get 3.78?

**Comment by Cchiyi** [comment]
maybe I need upgrade version to 1.20.3

**Comment by ohler55** [comment]
The issue is that OjG parses the decimal number as an integer part and a fractional part. The go core does math in base 2 so `3+78/100` results in what you are seeing. That approach in OjG uses gives better performance but with the inaccuracies of the go core past 16 significant digits the results when printed with the `%g` formatting option show additional digits instead of rounding as expected. You can see that in the following code snippet and try in the the go playground.

```go
package main

import "fmt"

func main() {
	fmt.Printf("%g\n", float64(3)+float64(78)/float64(100))
}
```

There is an easy work around in OjG. The `oj.DefaultOptions.FloatFormat` defaults to "%g". By changing that to "%.16g" the results will be rounded to the the safer 16 significant digits and the output will then be `3.78`.

**Comment by ohler55** [comment]
Did the explanation and setting suggestions make sense to you?

**Comment by ohler55** [comment]
No response, closing.
