### ISSUE TITLE
Error using jsonpath to find top level attribute with primitive value

### ISSUE THREAD

**Issue by cgreenlee-tc** [ohler55/ojg#46]
**JSON Input:**
{  
  "foo": "bar"
}

**JSONPath Expression:**
$[?(@.foo == "bar")]

**Expected results (from Jayway or Gatling, courtesy of http://jsonpath.herokuapp.com/):**
[
   {
      "foo" : "bar"
   }
]

**Results from calling expr.Get():**
nil

**Comment by ohler55** [comment]
As you probably noticed, there are 4 interpretations of how that combination of input and path on that site alone. OjG attempts to implement the original Goessner behaviour. Where the expected behaviour is vague my interpretation of the behaviour is used.  There is a site that builds a consensus of behaviours for JSONPath implementations at https://cburgmer.github.io/json-path-comparison. Without a clear and definitive JSONPath specification a consensus is about all that can be done to get a picture of how the various implementations compare.

The reason OjG returns and empty list with the above conditions is that filters apply to lists yet the input is not a list so there is nothing to filter hence the return of an empty list.

**Comment by cgreenlee-tc** [comment]
Fair, but frustrating.  Goessner's statement that "With JSONPath square brackets operate on the object or array addressed by the previous path fragment" does seem to imply that a filter within square brackets should operate on an object as well as an array.  Just to be clear, is there no way with OJG to say "Return the object if an only if it contains an attribute 'foo' with a value of 'bar'"?

**Comment by ohler55** [comment]
You can use the jp.Script to check if the data is a match. That will return true or false.

**Comment by ohler55** [comment]
Did that work for you?

**Comment by cgreenlee-tc** [comment]
I just wrapped any singleton object in an array during pre-processing to get what I needed.  It still feels like a strange gap in capability, especially compared to XPath.

**Comment by ohler55** [comment]
That's part of the reason that jp.Script is public. To allow those kind of checks on maps. I believe the logic in the JSONPath spec is that arrays and objects are different so matching against both as if they are the same would give inconsistent results.

**Comment by ohler55** [comment]
Can this be closed?
