### ISSUE TITLE
Concurrent Map Access Panic

### ISSUE THREAD

**Issue by raidancampbell** [ohler55/ojg#51]
Rarely, and under high load situations, we see a panic due to a concurrent map access.  I'm not entirely sure our code is innocent here, but the panic does occur within `ojg` version 1.9.5.  For reference, here's the relevant part of the stacktrace:

```
fatal error: concurrent map read and map write

goroutine 9084894 [running]:
runtime.throw(0x188b125, 0x21)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc004719200 sp=0xc0047191d0 pc=0x436e42
runtime.mapaccess2_faststr(0x160cf00, 0xc001bc3d10, 0xc00071ae38, 0x4, 0x44ed4e, 0xc00185b680)
	/usr/local/go/src/runtime/map_faststr.go:116 +0x47c fp=0xc004719270 sp=0xc004719200 pc=0x4150ac
github.com/ohler55/ojg/jp.Expr.Get(0xc000708a00, 0x4, 0x4, 0x160cf00, 0xc001bc3d10, 0x0, 0x19, 0x185af01)
	/builds/foo/bar/baz/.tmp/pkg/mod/github.com/ohler55/ojg@v1.9.5/jp/get.go:62 +0x64ad fp=0xc004719920 sp=0xc004719270 pc=0x132c11d

<omitted calling code>
```

Our usage looks like this:

```go
var extractor = mustParseExpr("$.foo.bar.baz")

func mustParseExpr(toBeParsed string) (x jp.Expr) {
	x, err := jp.ParseString(toBeParsed)
	if err != nil {
		panic(err)
	}
	return x
}

func doWork(msg []byte) {
    vals := extractor.Get(msg)
    // additional code omitted
}

```

**Comment by ohler55** [comment]
Before getting to the issue, the jp package doesn't have a MustParse as you noticed. Instead it has the easy build functions so you could use `x := jp.R().C("foo").C("bar").C("bad")` or just leave off the `R()` since it is optional. Of course for more complex expression the approach you took is very reasonable. Just wanted to pass along the hint.

As for the issue, if  I look at the OjG code I see that the provided data which is a map is being accessed but since the call to `Get()` is in a single go routine it must be colliding with some other part of the code. I would need to know more about the rest of the environment to nail it down further. Where is the map/data being created or written to?

**Comment by raidancampbell** [comment]
Thanks for the prompt response and usage tip!  Your comment was extremely insightful: I now believe my code is at fault here.  For closure, the flow of the issue is below:

```go
var event map[string]interface{}
_ = jsoniter.Unmarshal(msg, &event) // msg is []byte of json

go func() {
    // code that ultimately will call ojg's Get func
}

// code that overwrites a couple of keys in the map[string]interface{} populated by the jsoniter.Unmarshal call
```

I apologize for taking your time, but you've saved me quite a bit of time in finding the root cause.

**Comment by ohler55** [comment]
Glad to help. You can use OjG for the unmarshalling as well. It is faster than jsoniter when unmarshalling into a `map[string]interface{}`. I still have to optimize unmarshalling into a struct though.
