### ISSUE TITLE
Unintentional / Undocumented reuse of buffer?

### ISSUE THREAD

**Issue by Bios-Marcel** [ohler55/ojg#90]
Look at the following. The results are clearly wrong. I am not sure if this is intended behaviour, but if so, it isn't documented.

```go
package main

import (
	"fmt"

	"github.com/ohler55/ojg/oj"
)

func main() {
	type a struct {
		A string `json:"a"`
	}

	type b struct {
		B string `json:"b"`
	}

	aBytes, _ := oj.Marshal(a{
		A: "a",
	})
	bBytes, _ := oj.Marshal(b{
		B: "b",
	})

	fmt.Println(string(bBytes))
	fmt.Println(string(aBytes))

	//Output:
	//{"b":"b"}
	//{"b":"b"}
}

```

**Comment by ohler55** [comment]
It is wrong, I agree. The buffer is reused but for Marshal it should make a copy before returning. The Writer.MustJSON suffers the same although I might take a different approach with that one and add an optional argument to either copy or not since in many case reuse of the buffer is not an issue. It certainly is with your use case.

**Comment by ohler55** [comment]
Fixed and released as v1.14.3.

**Comment by ohler55** [comment]
Thanks for letting me know.

**Comment by Bios-Marcel** [comment]
I'll just close this. I'll trust that you've fixed this ^^

I just evaluated the library for a new project.

**Comment by ohler55** [comment]
Thanks. I did create a unit test for it and verified it failed before the fix and not after.
