### ISSUE TITLE
jp feature request: Set() that only replaces existing values

### ISSUE THREAD

**Issue by juliannguyen4** [ohler55/ojg#99]
Currently Set() will insert any new values in lists and maps if they don't exist. Is there a way to call Set() so it only replaces existing matching items?

For example, this code:
```
expr, err := jp.ParseString(jsonPath)
expr.Set(document, 10)
```
with this document:
```
{
    "map": {
        "int": 4
    }
}
```
should only replace the value of "int" in the nested map:
```
{
    "map": {
        "int": 10
    }
}
```

Right now, `Set()` would insert a key-value pair of "int" and 10 in every matching location:
```
{
    "map": {
        "int": 10
    }
    "int": 10
}
```

**Comment by ohler55** [comment]
The first document is not a valid JSON document. There is not function to check for existence and then set but you can combine a get with a set. Use the filter for exists and then set.

**Comment by ohler55** [comment]
Does that answer your question? If so can this issue be closed?

**Comment by juliannguyen4** [comment]
Hi @ohler55, I tried the solution you proposed, but I had trouble implementing it because there's a lot of overhead to create a filter expression for each existing path in the JSON document. But I think it would benefit a lot of people to have a `Set()` for only existing values, since it is a common operation to update existing data fields in a document.

**Comment by ohler55** [comment]
I'm not sure I follow. Can you give an example?

**Comment by ohler55** [comment]
I see the example above was updated but without the path used it's hard to tell why you would get the result you did. Was it `$..int`?

**Comment by ohler55** [comment]
I'm still not sure what you were looking for but if the intent was to replace any occurrence of `"int": 4` anywhere in the json then `$..[?(@.int == 4)].int` would be the JSONPath to use. If that wasn't the intent then please provide the path you were trying to use and I'll reopen the issue.

Closing due to no response.

**Comment by juliannguyen4** [comment]
Hi @ohler55, sorry I was on vacation for the holidays and I wasn't able to get back to you until now.

Yes, the jsonpath was `$..int`, and the intent was to replace every existing occurrence of `int` in the document. I should've made that more clear.

**Comment by ohler55** [comment]
Try `$..[?(@.int != null)].int` and see if that does what you want.

**Comment by juliannguyen4** [comment]
That seems to work. Thanks for making that suggestion!

**Comment by juliannguyen4** [comment]
> Try $..[?(@.int != null)].int and see if that does what you want.

This method works for replacing every existing item with the same value, but it doesn't work for more advanced operations.

Right now, I'm writing a method to append to every list that matches a JSON path. For example, with JSON path`$..list`, I want to append the number 4 to every matching list:
```
{
    "map1": {
        "list": [1, 2, 3]
    },
    "map2": {
        "list": [0, 1, 2]
    }
}
```
The expected results should be:
```
{
    "map1": {
        "list": [1, 2, 3, 4] # 4 appended to this list
    },
    "map2": {
        "list": [0, 1, 2, 4] # 4 appended to this list
    }
}
```
Do you have a way to do this?

**Comment by ohler55** [comment]
There is not a way to do that in the current release. It would require a change in the API with a new function since the modified slice would change and that would have to be passed back to the caller. That is similar to the recent addition of the Remove() functions for the jp package. It would also require a new variation to JSONPath to differentiate between a set and an append.

**Comment by thadguidry** [comment]
It seems as if the Union operator `[,]` could help somehow?
> <html>
<body>


[,] | Union operator in XPath results in a combination of node sets. JSONPath allows alternate names or array indices as a set.
-- | --



</body>
</html>

`list: [0, 1, 2, 3][*,"4"]`

I personally love the `<<` leftShift operator (push method) in other languages like Java, Ruby, etc. to append to a list.

But the JsonPath function is really `append(X)` or alternatively if you need stricter typing extending the list you could use `concat(X)`.

@ohler55 have you given broader thought that OJG eventually expands more with additional operators like they did in https://www.npmjs.com/package/jsonpath-plus.  I ask because of your last sentence that seems as if you are OK with deviating from JSONPath (Stefann Goessner implementation)

**Comment by thadguidry** [comment]
Totally agree.  Finding elements is different from changing elements.

**Comment by ohler55** [comment]
I was thinking of this:

```
func (x Expr) Modify(data any, modifier func(element any) (newElement any, changed bool)) any {
        // the code
        return data
}
```

The data elements are found and passed to the modifier and the result then set in the data. Can be used for appends, inserts, sorting, or what ever is desired.

**Comment by juliannguyen4** [comment]
Hi @ohler55, that would be great but why does the modifier function need to return `changed`? Wouldn't this function apply to all the matches in the document?

**Comment by ohler55** [comment]
Yes to both questions. It would return the changed data and it would apply to all the matches. It's up to the provided function to decide what to do.

**Comment by juliannguyen4** [comment]
In the modifier function, how would it access `data` in `Modify()`? For example, if I wanted to append `data` to `element` and return the result as `newElement`.

**Comment by ohler55** [comment]
It might take a few weeks depending on my work schedule.

**Comment by ohler55** [comment]
Or it could take a day. Expect a branch (jp-modify) for review in a couple of hours. Expr.Remove() has been reimplemented to use the Expo.Modify() function. Just need more tests and it will be ready.

**Comment by ohler55** [comment]
Released v1.17.0 with Expr.Modify()

**Comment by juliannguyen4** [comment]
Hi @ohler55, thank you so much for releasing this!

Right now, I think I have found an issue in `Modify()`. A JSON path containing recursive descent doesn't seem to work:

```go
package main
import (
	"fmt"
	"github.com/ohler55/ojg/jp"
)

func main() {
	expr := jp.MustParseString("$..int")
	var data any
	data = map[string]any{
		"a": []any{
			map[string]any{
				"int": 1,
			},
		},
	}

	modifier := func(_ any) (any, bool) {
		return 4, true
	}
	data, err := expr.Modify(data, modifier)
	if err != nil {
		panic("error")
	}
	
	fmt.Println(data)
}
```
Output:
```
map[a:[map[int:1]]]
```

**Comment by ohler55** [comment]
Descent are a difficult one. An error is returned if the last fragment is a descent. Being the second to last should be okay though. Let me look at this tonight.

**Comment by ohler55** [comment]
Fixed in the "fix-modify-descent" branch. If you have the time give it a try.

**Comment by thadguidry** [comment]
Fixed in PR #105

**Comment by juliannguyen4** [comment]
Hi @ohler55, that branch fixes the problem so I really appreciate that. Could you create a release for it please?

**Comment by ohler55** [comment]
done
